cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/download # Sufficient to add miniconda.sh to TRAVIS cache.
    - $HOME/miniconda2 # Add the installation to TRAVIS cache.

dist: xenial

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - ./.travis/travis_before_install.sh
  - export PATH=/home/travis/miniconda2/bin:$PATH

install:
  - ./.travis/travis_install.sh
  - source activate pyenv
  - conda install -y pytorch torchvision cpuonly -c pytorch
  - pip install pytest
  - pip install flake8
  - pip install -r requirements.txt
  - pip install .

jobs:
  - &normaltest
    stage: test
    python: "3.6"
  - <<: *normaltest
    python: "3.7"
  - <<: *normaltest
    python: "3.8"

script:
  - python --version
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - echo "$PART"
  - python -c 'import torch; print(torch.__version__)'
  - python -c 'import neuralnet_pytorch; print(neuralnet_pytorch.__version__)'
  - python -m pytest -sv tests/
  - flake8 neuralnet_pytorch

after_failure:
- cat /home/travis/.pip/pip.log